//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.InsuredEmployee = new HashSet<InsuredEmployee>();
        }
        
        public int Id { get; set; }
        public System.DateTime ConclusionDate { get; set; }
        public System.DateTime CotractTerm { get; set; }
        public string AmountPayments { get; set; }
        public int InsurancePayments { get; set; }
        public Nullable<int> IdInsuranceAgent { get; set; }
    
        public virtual InsuranceAgent InsuranceAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuredEmployee> InsuredEmployee { get; set; }
    }
}
