//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAgency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationalPracticeBDEntities1 : DbContext
    {
        private static EducationalPracticeBDEntities1 _context;
        public EducationalPracticeBDEntities1()
            : base("name=EducationalPracticeBDEntities1")
        {
        }

        public static EducationalPracticeBDEntities1 GetContext()
        {
            if (_context == null)
                _context = new EducationalPracticeBDEntities1();
            
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<InsuranceAgent> InsuranceAgent { get; set; }
        public virtual DbSet<InsuredEmployee> InsuredEmployee { get; set; }
    }
}
