//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuredEmployee
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public int Age { get; set; }
        public int Category { get; set; }
        public int IdCompany { get; set; }
        public int IdContract { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
